//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class accUserRole
    {
        public int ID { get; set; }
        public byte userID { get; set; }
        public byte roleID { get; set; }
    
        public virtual accRole accRole { get; set; }
        public virtual accUser accUser { get; set; }
    }
}
