//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class errMessage
    {
        public int ID { get; set; }
        public string logLevel { get; set; }
        public string message { get; set; }
        public string exception { get; set; }
        public System.DateTime logDate { get; set; }
        public bool isWarned { get; set; }
    }
}
