//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class schScheduleJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schScheduleJob()
        {
            this.schScheduleLogs = new HashSet<schScheduleLog>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public System.TimeSpan scheduleTime { get; set; }
        public int frequency { get; set; }
        public string webServiceUrl { get; set; }
        public string parameter { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schScheduleLog> schScheduleLogs { get; set; }
    }
}
