//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertising
    {
        public int ID { get; set; }
        public byte zoneID { get; set; }
        public string message { get; set; }
        public Nullable<bool> isMale { get; set; }
        public Nullable<byte> minAge { get; set; }
        public Nullable<byte> maxAge { get; set; }
    }
}
