//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerService()
        {
            this.tblCustomerAnswers = new HashSet<tblCustomerAnswer>();
        }
    
        public int ID { get; set; }
        public int customerID { get; set; }
        public byte zoneID { get; set; }
        public Nullable<short> groupID { get; set; }
        public Nullable<short> classID { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> contentID { get; set; }
        public byte serviceStatusID { get; set; }
        public string sendSmsRequestID { get; set; }
        public bool answerWait { get; set; }
        public byte statusID { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public Nullable<System.DateTime> answerDate { get; set; }
        public int score { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblContent tblContent { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerAnswer> tblCustomerAnswers { get; set; }
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblServiceStatu tblServiceStatu { get; set; }
        public virtual tblZone tblZone { get; set; }
    }
}
