//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionOption
    {
        public int ID { get; set; }
        public int questionID { get; set; }
        public string answerOption { get; set; }
        public byte score { get; set; }
    
        public virtual tblQuestion tblQuestion { get; set; }
    }
}
