//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTelegramCustomerService
    {
        public int ID { get; set; }
        public int customerID { get; set; }
        public byte zoneID { get; set; }
        public string ticket { get; set; }
        public string telegramID { get; set; }
        public Nullable<byte> telegramStatusID { get; set; }
        public Nullable<short> telegramContentID { get; set; }
        public Nullable<byte> serviceStatusID { get; set; }
        public byte statusID { get; set; }
        public System.DateTime createDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblServiceStatu tblServiceStatu { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblStatu tblStatu1 { get; set; }
        public virtual tblTelegramContent tblTelegramContent { get; set; }
        public virtual tblZone tblZone { get; set; }
    }
}
