//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTelegramContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTelegramContent()
        {
            this.tblTelegramCustomerServices = new HashSet<tblTelegramCustomerService>();
        }
    
        public short ID { get; set; }
        public System.Guid uID { get; set; }
        public int code { get; set; }
        public byte zoneID { get; set; }
        public Nullable<int> contentID { get; set; }
        public string context { get; set; }
        public byte[] media { get; set; }
    
        public virtual tblContent tblContent { get; set; }
        public virtual tblZone tblZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTelegramCustomerService> tblTelegramCustomerServices { get; set; }
    }
}
