//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwContent
    {
        public int ID { get; set; }
        public int code { get; set; }
        public byte zoneID { get; set; }
        public short groupID { get; set; }
        public short classID { get; set; }
        public string context { get; set; }
        public string question { get; set; }
        public Nullable<byte> optionCount { get; set; }
        public string answer { get; set; }
        public Nullable<long> rowNo { get; set; }
    }
}
