//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateDataFromOldDbToMatlabDb.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCustomerScore
    {
        public Nullable<bool> status { get; set; }
        public Nullable<long> rowNo { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public Nullable<System.DateTime> answerDate { get; set; }
        public int score { get; set; }
        public byte zoneID { get; set; }
    }
}
