//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matlab.Api.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Matlab.Api.Tools.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر به سوال پاسخ داد.
        /// </summary>
        internal static string AnsweredArticle {
            get {
                return ResourceManager.GetString("AnsweredArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت دسته بندی ها.
        /// </summary>
        internal static string CategoriesRequested {
            get {
                return ResourceManager.GetString("CategoriesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت جعبه تغییر کرد.
        /// </summary>
        internal static string ChangeBoxState {
            get {
                return ResourceManager.GetString("ChangeBoxState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مضعیت جعبه تغییر کرد.
        /// </summary>
        internal static string ChangeBoxStateValue {
            get {
                return ResourceManager.GetString("ChangeBoxStateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مطلب را مطالعه کرد.
        /// </summary>
        internal static string LearnedArticle {
            get {
                return ResourceManager.GetString("LearnedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت جعبه های بسته.
        /// </summary>
        internal static string PackageBoxesRequested {
            get {
                return ResourceManager.GetString("PackageBoxesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت بسته های دسته بندی.
        /// </summary>
        internal static string PackagesOfCategoryRequested {
            get {
                return ResourceManager.GetString("PackagesOfCategoryRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت بسته های کاربر.
        /// </summary>
        internal static string PackagesOfUserRequested {
            get {
                return ResourceManager.GetString("PackagesOfUserRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات پروفایل.
        /// </summary>
        internal static string ProfileDataRequested {
            get {
                return ResourceManager.GetString("ProfileDataRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت راهنمای سوال.
        /// </summary>
        internal static string QuestionHintRequested {
            get {
                return ResourceManager.GetString("QuestionHintRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال دیده شد.
        /// </summary>
        internal static string QuestionViewdRequested {
            get {
                return ResourceManager.GetString("QuestionViewdRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر نماد کاربر.
        /// </summary>
        internal static string SetAvatarRequested {
            get {
                return ResourceManager.GetString("SetAvatarRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت مطالب جعبه کاربر.
        /// </summary>
        internal static string UserPackageBoxArticlesRequested {
            get {
                return ResourceManager.GetString("UserPackageBoxArticlesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت جعبه های بسته کاربر.
        /// </summary>
        internal static string UserPackageBoxesRequested {
            get {
                return ResourceManager.GetString("UserPackageBoxesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت سوالات جعبه کاربر.
        /// </summary>
        internal static string UserPackageBoxQuestionsRequested {
            get {
                return ResourceManager.GetString("UserPackageBoxQuestionsRequested", resourceCulture);
            }
        }
    }
}
