//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matlab.Api.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Matlab.Api.Tools.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای عکس خالیست.
        /// </summary>
        internal static string ImageEmpty {
            get {
                return ResourceManager.GetString("ImageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم پشتیبانی از فرمت عکس.
        /// </summary>
        internal static string ImageFileFormat {
            get {
                return ResourceManager.GetString("ImageFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم عکس بیشتر از استاندارد است.
        /// </summary>
        internal static string ImageFileSize {
            get {
                return ResourceManager.GetString("ImageFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند عکس ارسال شده.
        /// </summary>
        internal static string ImageMultiUploaded {
            get {
                return ResourceManager.GetString("ImageMultiUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس دریافت نشد.
        /// </summary>
        internal static string ImageNotSent {
            get {
                return ResourceManager.GetString("ImageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سرور.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل معتبر نیست.
        /// </summary>
        internal static string MobileInvalid {
            get {
                return ResourceManager.GetString("MobileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی معتبر نیست.
        /// </summary>
        internal static string NationalCodeInvalid {
            get {
                return ResourceManager.GetString("NationalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی الزامیست.
        /// </summary>
        internal static string NationalCodeRequied {
            get {
                return ResourceManager.GetString("NationalCodeRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحیح.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاراکتر های نامعتبر در رمز عبور.
        /// </summary>
        internal static string PasswordInvalidCharacter {
            get {
                return ResourceManager.GetString("PasswordInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول نامناسب رمز عبور.
        /// </summary>
        internal static string PasswordInvalidLenght {
            get {
                return ResourceManager.GetString("PasswordInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار آن مطابق نیستند.
        /// </summary>
        internal static string PasswordInvalidMatch {
            get {
                return ResourceManager.GetString("PasswordInvalidMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر دارای خطا هستند.
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی مورد نظر یافت نشد.
        /// </summary>
        internal static string RequestedCategoryNotFound {
            get {
                return ResourceManager.GetString("RequestedCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل الزامیست.
        /// </summary>
        internal static string RequierdMobile {
            get {
                return ResourceManager.GetString("RequierdMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور الزامیست.
        /// </summary>
        internal static string RequierdPassword {
            get {
                return ResourceManager.GetString("RequierdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفقیت آمیز.
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته مورد نظر برای کاربر تعریف نشده است.
        /// </summary>
        internal static string UserPackageNotFound {
            get {
                return ResourceManager.GetString("UserPackageNotFound", resourceCulture);
            }
        }
    }
}
